FROM otel/opentelemetry-collector-contrib:latest

LABEL maintainer="pythonicshahdev"
LABEL description="OpenTelemetry Collector for Boomi traces"
LABEL version="1.0.0"

# Copy custom configuration
COPY otel-collector-config.yaml /etc/otelcol-contrib/config.yaml

# Expose OTLP ports
EXPOSE 4317 4318


CMD ["--config=/etc/otelcol-contrib/config.yaml"]
