receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 10s
    send_batch_size: 1024

exporters:
  elasticsearch/logs:
    endpoints: ["http://opensearch:9200"]
    logs_index: boomi-logs
    mapping:
      mode: ecs
  elasticsearch/metrics:
    endpoints: ["http://opensearch:9200"]
    logs_index: boomi-metrics
    mapping:
      mode: ecs
  opensearch/traces:
    http:
      endpoint: "http://opensearch:9200"
      timeout: 30s
    logs_index: boomi-traces

service:
  telemetry:
    metrics:
      level: detailed
  pipelines:
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [elasticsearch/logs]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [elasticsearch/metrics]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [opensearch/traces]
