receivers:
  otlp/from_vector:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4321
  otlp/from_boomi:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 10s
    send_batch_size: 1024

exporters:
  elasticsearch/logs:
    endpoints: ["http://opensearch:9200"]
    logs_index: boomi-logs
    sending_queue:
      enabled: true
    retry_on_failure:
      enabled: true
  elasticsearch/metrics:
    endpoints: ["http://opensearch:9200"]
    logs_index: boomi-metrics
    sending_queue:
      enabled: true
    retry_on_failure:
      enabled: true
  opensearch/traces:
    http:
      endpoint: "http://opensearch:9200"
      timeout: 30s
    logs_index: boomi-traces
    sending_queue:
      enabled: true
    retry_on_failure:
      enabled: true

service:
  telemetry:
    metrics:
      address: 0.0.0.0:8888
  pipelines:
    logs:
      receivers: [otlp/from_vector]
      processors: [batch]
      exporters: [elasticsearch/logs]
    metrics:
      receivers: [otlp/from_vector]
      processors: [batch]
      exporters: [elasticsearch/metrics]
    traces:
      receivers: [otlp/from_boomi]
      processors: [batch]
      exporters: [opensearch/traces]
