[sources.boomi_otel]
type = "opentelemetry"

[sources.boomi_otel.grpc]
address = "0.0.0.0:4317"

[sources.boomi_otel.http]
address = "0.0.0.0:4318"

[transforms.logs_transformed]
type = "remap"
inputs = ["boomi_otel.logs"]
source = '''
.ingestion_timestamp = now()
.data_source = "boomi"

if exists(.attributes) {
  .attributes_raw = encode_json(.attributes)
  del(.attributes)
}
'''

[transforms.metrics_transformed]
type = "remap"
inputs = ["boomi_otel.metrics"]
source = '''
.ingestion_timestamp = now()
.data_source = "boomi"
'''

[sinks.otel_collector_forward]
type = "http"
inputs = ["logs_transformed", "metrics_transformed"]
uri = "http://otel-collector:4321"
encoding.codec = "json"
